# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-10 22:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talk_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coach',
            options={'verbose_name_plural': 'coaches'},
        ),
        migrations.RemoveField(
            model_name='team',
            name='location',
        ),
        migrations.AddField(
            model_name='team',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='staic/talk_app/img'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='coaching_style',
            field=models.CharField(choices=[('Off', 'Offensive'), ('Def', 'Defensive'), ('Bal', 'Balanced')], max_length=3),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('PG', 'Point Guard'), ('SG', 'Shooting Guard'), ('SF', 'Small Forward'), ('PF', 'Power Forward'), ('C', 'Center')], max_length=2),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='talk_app.Team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='coach',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='talk_app.Coach'),
        ),
    ]
