# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-10 00:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talk_app', '0002_auto_20160810_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='coach',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='talk_app.Coach'),
        ),
    ]
